molssi-seamm/seamm

.codecov.yml
.travis.yml
Makefile
devtools/README.md
devtools/conda-envs/test_env.yaml
devtools/scripts/create_conda_env.py
devtools/travis-ci/before_install.sh

Switched to using conda environments with Travis-CI, and fully implemented jobs so that we run lint first, then tests, and then -- if appropriate -- upload to PyPi.

Travis setup with conda

---

devtools/conda-envs/test_env.yaml
devtools/travis-ci/before_install.sh
requirements.txt
requirements_dev.txt
requirements_install.txt
seamm/node.py
seamm/templates/line.graph_template
seamm/templates/line.html_template

Templates for reasonable line plots, either creating plotly json as
.graph files, or standalone html files.

Added plotting capabilities to the base node, and templates for plots.

---

docs/conf.py
requirements.txt
requirements_install.txt
seamm/tk_node.py
setup.py

Expanded results panel to handle both a calculation and method

---

seamm/node.py

Moved the instance variable `bibliography` to `_bibliography` so that
it is not written to the flowchart, and upgraded `to_dict()` to ignore
all but specified attributes starting with and underscore. `_uuid` is
the main exception.
Finally, in order to facilitate debugging, added an optional logger to
the initializer and changed all logger commands to using the instance
variable. By default it is still the file-local logger, but this
allows subclasses to pass in their logger, controlled by a command
line option such as --packmol-log-level to allow more precise
debugging.

Changes to support citations better.

---

seamm/__init__.py
seamm/argument_parser.py
seamm/exec_flowchart.py
seamm/flowchart.py
seamm/node.py
seamm/run_flowchart.py
seamm/tk_job_handler.py
seamm/tk_node.py

Replacing configargparse with a custom solution for parsing the command line and using a config (.ini) file. The entire command line is parsed once at the beginning and options passed to all steps in the flowchart. As a result, help now works properly and the new ControlParameters plug-in is supported.

Option handling

---

seamm/flowchart.py
seamm/graph.py
seamm/node.py

Something changed with the handling of the UUID in the initialization of nodes that resulted in two steps getting the same UUID, and hence failing when try to add the second node to the graph.

Closes Issue#90: problem with adding two or more steps to a flowchart.

---

requirements.txt
requirements_install.txt
seamm/flowchart.py
seamm/node.py
seamm/run_flowchart.py

Added metadata to the flowchart including digests, and uuid to job_data.out.
Also added headers to the files and use standard formatting for the flowchart to
make it easier to get parts of the data.

Added digests to flowcharts and UUIDs for jobs

---

seamm/__init__.py
seamm/exec_flowchart.py
seamm/node.py
seamm/standard_parameters.py

Basic functionality for putting new structures into the current configuration, overwriting it, or creating a new configuration or system.

Generalized system handling

---

.zenodo.json

Unfortunately, to test whether this all works I have to make a new release! No change in functionality.

Added metadata for Zenodo DOI.

---

seamm/tk_job_handler.py
seamm/tk_open.py

Fixed issues requesting and storing the passwords for a dashboard.
Fixed bug opening a flowchart if ~/SEAMM/flowcharts does not exist.

Bugfix: credentials for dashboards and flowchart directory.

---

Makefile
devtools/conda-envs/test_env.yaml
requirements.txt
seamm/__init__.py
seamm/dashboard_handler.py
seamm/seammrc.py
seamm/tk_job_handler.py
seamm/tk_open.py

Refactored code and save current approach to opening flowcharts, a list of visited local directories etc. in the `~/.seammrc` file so that the next call to open starts where the user left off.

Enhancements for opening flowcharts

---

HISTORY.rst
seamm/node.py
seamm/tk_node.py

Simplified the handling of
- results and properties so that plug-ins do less, and handling is triggered by presence of metadata
- subflowcharts, again so that plug-ins need less code.

Improvements to simplify plug-ins and the cookie cutter

---

seamm/run_flowchart.py
seamm/tk_job_handler.py

- Fixed issues that had crept in running from the command-line but inserting into the datastore
- Improved the handling of the title and description for both command-line and Dashboard jobs, defaulting each to that stored in the flowchart.

Improvement for running jobs

---

HISTORY.rst
seamm/exec_flowchart.py
seamm/node.py

Also catch and report any errors writing out the final structure for viewing.

Added support for keyed columns in table output

---

HISTORY.rst
seamm/node.py
seamm/run_flowchart.py
seamm/standard_parameters.py

* Added ability to name systems and configurations with the IUPAC name, InChI, or InChIKey of the configuration.
* Generally cleaned up and streamlined the code handling new systems and configurations.

Extending and cleaning up handling of configurations

---

HISTORY.rst
seamm/run_flowchart.py
seamm/tk_job_handler.py

The previous change to allow running "flowchart.flow" in the current directory caused a bug in other scenarios.

Bugfix: running flowcharts from the commandline.

---

HISTORY.rst
seamm/node.py

- Fixed an issue getting the date of a plug-in for development versions of the plug-in. This did not affect end users, but did casue issues for development.

Corrected issue with citations in development versions

---

HISTORY.rst
seamm/templates/surface.graph_template
seamm/templates/surface.html_template
seamm/tk_node.py

* Dialogs that have a Results tab -- mainly the computational engines -- raised an error if the "Cancel" button was clicked. "OK" worked. This fixes the problem.
* Added graph templates for 3-D graphs with e.g. energy vs X, Y.

Bugfix: Error when clicking "Cancel" on some dialogs

---

HISTORY.rst
seamm/templates/band_structure.html_template
seamm/templates/line.graph_template
seamm/templates/line.html_template
seamm/templates/surface.html_template

* Added multiple axes to line graphs.
* Updated to correct version of plotly. 'latest' is actually not.

Enhancements to line graphs

---

HISTORY.rst
seamm/standard_parameters.py

* The standard structure handling widgets and methods had an error is the approach was a variable rather than one of the choices.

Bugfix: Error using variable in stucture handling

---

HISTORY.rst
seamm/node.py

* Removed debug printing that was accidentally left in the flowchart code.

Bugfix: removed debug printing in the flowchart

---

HISTORY.rst
seamm/node.py
seamm/standard_parameters.py

* Added ability to ignore or discard a structure from e.g. optimization
* Added isomeric SMILES to the possible names for systems and configurations

Added isomeric SMILES to structure names and ability to discard

---

HISTORY.rst
seamm/standard_parameters.py

* Changed the standard option to "Discard the structure" to indicate that the structure should not be saved in the database.

Changed option to "Discard the structure"

---

HISTORY.rst
seamm/__main__.py
seamm/node.py
seamm/parameters.py

* Fixed a bug that occurred trying to set the name of a system or configuration to early, when it had atoms, causing errors.

Bugfix: Error naming systems and configurations

---

HISTORY.rst
seamm/node.py
seamm/parameters.py
seamm/standard_parameters.py
seamm/tk_node.py
seamm/variables.py

- Fixed an error that occurred sometimes when setting the name of the system and/or configuration.

Bugfix: error in setting name of system & configuration

---

HISTORY.rst
seamm/variables.py

* Fixed an issue that caused a crash handling f-strings in some parameters in the GUI.

Bugfix: Error handling f-strings in variables

---

HISTORY.rst
seamm/__main__.py
seamm/node.py
seamm/parameters.py

* Added better control over the width of widgets displaying parameters.
* Catch and report errors storing properties to the database, but continue on in any case.

Small enhancements and catching errors.
